### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by andela-efortune**

### CODE REVIEW

**Comment by texyh** [comment]
fortune na wetin na

**Comment by andela-efortune** [comment]
I'm sorry Sir, but don't you think it makes more sense if our little tidy app would server more like a flask starter boilerplate?

**Comment by texyh** [comment]
I dnt get u bro

**Comment by andela-efortune** [comment]
Remember if you need to start a flask project you'll have to do some annoying setup which can be time consuming. We can convert this project to an open source project, which is basically a boilerplate for a flask app to save a developer all those setup time. So what they could do is `git clone` the project `cd...` into it and run `pip install` and have some setup time saved. Makes sense? :smirk:

**Comment by texyh** [comment]
Wetin be starting dependencies

**Comment by andela-efortune** [comment]
Starting dependencies? Where is that?

**Comment by texyh** [comment]
Nigga cnt we jst chat on slack

**Pull request merged**
